site_name: cypress.blog
site_description: cypress的技术博客以及日常生活记录
site_author: cypress
site_url: https://cyprer.github.io/blog0/
theme:
  name: material
  features:
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - content.code.copy #代码复制
  palette:
    # 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式

    # 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

markdown_extensions:
  - toc:
      permalink: true        # 添加段落链接
      toc_depth: 3          # 目录深度
      separator: "_"        # 标题锚点分隔符
      title: "目录"         # 目录标题
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true  # 显示行号
      use_pygments: true
      pygments_style: monokai  # 设置高亮风格
plugins:
  - search:
      lang: 
      - zh
      - en
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      post_excerpt: optional


nav:
      - 笔记:
          - jvm:
            - 字节码增强技术: note/jvm/bytecode-enhancement.md
            - 类加载机制: note/jvm/class-loading.md
            - 内存模型: note/jvm/memory-structure.md
            - 垃圾回收机制: note/jvm/garbage-collection.md

          - 微服务技术栈:
            - eureka: note/microservice/eureka.md
            - ribbon: note/microservice/ribbon.md
            - nacos: note/microservice/nacos.md
            - Feign: note/microservice/feign.md
            - gateway: note/microservice/gateway.md
          - 数据结构:
              - 代码随想录:
                  - 数组:
                      - 二分查找: note/datastructure/array/binary-search.md
                      - 快慢指针: note/datastructure/array/fast-slow-pointer.md
                      - 双指针: note/datastructure/array/double-pointer.md
                      - 滑动窗口: note/datastructure/array/sliding-window.md
                      - 螺旋矩阵: note/datastructure/array/spiral-matrix.md
                      - 区间和: note/datastructure/array/interval-sum.md
                      - 分配土地: note/datastructure/array/land-allocation.md
              - 刷题日记:
                - 2025:
                  - 3月:
                    - 8号: note/datastructure/diary/2025/3month/8.md
                    - 9号: note/datastructure/diary/2025/3month/9.md
                    - 10号: note/datastructure/diary/2025/3month/10.md
                    - 11号: note/datastructure/diary/2025/3month/11.md
                    - 12号: note/datastructure/diary/2025/3month/12.md
                    - 13号: note/datastructure/diary/2025/3month/13.md
                    - 14号: note/datastructure/diary/2025/3month/14.md
                    - 15号: note/datastructure/diary/2025/3month/15.md
                    - 16号: note/datastructure/diary/2025/3month/16.md
                    - 17号: note/datastructure/diary/2025/3month/17.md
                    - 18号: note/datastructure/diary/2025/3month/18.md
                    - 19号: note/datastructure/diary/2025/3month/19.md
                    - 20号: note/datastructure/diary/2025/3month/20.md
                    - 21号: note/datastructure/diary/2025/3month/21.md
                    - 22号: note/datastructure/diary/2025/3month/22.md
                    - 23号: note/datastructure/diary/2025/3month/23.md
                    - 24号: note/datastructure/diary/2025/3month/24.md
                    - 25号: note/datastructure/diary/2025/3month/25.md
                    - 26号: note/datastructure/diary/2025/3month/26.md
                    - 27号: note/datastructure/diary/2025/3month/27.md
                    - 29号: note/datastructure/diary/2025/3month/29.md
                    - 31号: note/datastructure/diary/2025/3month/31.md
                  - 4月:
                    - 1号: note/datastructure/diary/2025/4month/1.md
                    - 2号: note/datastructure/diary/2025/4month/2.md
                    - 3号: note/datastructure/diary/2025/4month/3.md
                    - 4号: note/datastructure/diary/2025/4month/4.md
                    - 5号: note/datastructure/diary/2025/4month/5.md
                    - 6号: note/datastructure/diary/2025/4month/6.md
                    - 7号: note/datastructure/diary/2025/4month/7.md
                    - 8号: note/datastructure/diary/2025/4month/8.md
                    - 9号: note/datastructure/diary/2025/4month/9.md
                    - 10号: note/datastructure/diary/2025/4month/10.md
                    - 11号: note/datastructure/diary/2025/4month/11.md
                    - 13号: note/datastructure/diary/2025/4month/13.md
                    - 14号: note/datastructure/diary/2025/4month/14.md
                    - 15号: note/datastructure/diary/2025/4month/15.md
                    - 16号: note/datastructure/diary/2025/4month/16.md
                    - 17号: note/datastructure/diary/2025/4month/17.md
                    - 18号: note/datastructure/diary/2025/4month/18.md
                    - 19号: note/datastructure/diary/2025/4month/19.md
          - 计组:
            - csapp: note/cs_composition/csapp.md
            - cs61c:
                - knowledge:
                  - 内存管理: note/cs_composition/cs61c/knowledge/memory_management.md
                  - 浮点数: note/cs_composition/cs61c/knowledge/floating-point.md
                  - risv-v: note/cs_composition/cs61c/knowledge/risv-v.md
                - labs:
                  - lab1: note/cs_composition/cs61c/labs/lab1.md
                - projects:
                  - project1: note/cs_composition/cs61c/projects/project1.md
          - 计网: 
            - cs16825su: 
              - note/cs_net/cs168.md
              - TCP: note/cs_net/tcp.md
          - 操作系统: 
            - note/os/os.md
          - 其他:
            - 图灵完备: note/others/turing.md
            - 建站教程: note/others/site-construction.md
          - ssm:
            - hmdp: 
              - 登录: note/ssm/hmdp/login.md
              - 优惠卷秒杀: note/ssm/hmdp/voucher.md
            - spring:  note/ssm/spring.md
            - springmvc: note/ssm/springmvc.md
            - mybatis: note/ssm/mybatis.md
      - 项目:
          - redis:
              - 服务端: projects/redis/server.md
              - Resp协议解析: projects/redis/resp.md
              - 渐进式哈希实现Dict和rediscore接口的完善和实现: projects/redis/rehash.md
          - 大营销系统:
              - 需求设计:
                  - 营销场景的需求设计: projects/marketing/demand.md
              - 抽奖设计:
                  - 基础层持久化数据: projects/marketing/persistence.md
                  - 抽奖概率权重设计: projects/marketing/probability.md
                  - 抽奖过滤: projects/marketing/filter.md
              - 设计模式:
                  - 模板模式: projects/marketing/template.md
                  - 责任链和规则树模式: projects/marketing/chain_and_tree.md
          - 小型支付商城:
              - 架构理论:  
                  - DDD架构概念:  projects/spm/1.1.md
                  - DDD建模方法: projects/spm/1.2.md
                  - 工程模型: projects/spm/1.3.md
              - 需求设计:
                  - 需求prd讲解: projects/spm/2.1.md
                  - 工程四色建模设计: projects/spm/2.2.md
                  - 支付订单场景表设计: projects/spm/2.3.md
      - summary:
          - 2025年:
              - 1月: 
                  - summary/25year/1month/index.md
                  - 第一周: summary/25year/1month/1week.md
                  - 第二周: summary/25year/1month/2week.md
                  - 第三周: summary/25year/1month/3week.md
                  - 第四周: summary/25year/1month/4week.md
              - 2月:
                  - summary/25year/2month/index.md
                  - 第一周: summary/25year/2month/1week.md
                  - 第二周: summary/25year/2month/2week.md
                  - 第三周: summary/25year/2month/3week.md
                  - 第四周: summary/25year/2month/4week.md
              - 3月:
                  - summary/25year/3month/index.md
                  - 第一周: summary/25year/3month/1week.md
                  - 第二周: summary/25year/3month/2week.md
                  - 第三周: summary/25year/3month/3week.md
                  - 第四周: summary/25year/3month/4week.md
                  - 第五周: summary/25year/3month/5week.md
              - 4月:
                  - summary/25year/4month/index.md
                  - 第一周: summary/25year/4month/1week.md
                  - 第二周: summary/25year/4month/2week.md
                  - 第三周: summary/25year/4month/3week.md
                  - 第四周: summary/25year/4month/4week.md
              - 5月:
                  - summary/25year/5month/index.md
                  - 第一周: summary/25year/5month/1week.md
                  - 第二周: summary/25year/5month/2week.md
                  - 第三周: summary/25year/5month/3week.md
                  - 第四周: summary/25year/5month/4week.md
              - 6月:
                  - summary/25year/6month/index.md
                  - 第一周: summary/25year/6month/1week.md
                  - 第二周: summary/25year/6month/2week.md
                  - 第三周: summary/25year/6month/3week.md
                  - 第四周: summary/25year/6month/4week.md
                  - 第五周: summary/25year/6month/5week.md
              - 7月:
                  - summary/25year/7month/index.md
                  - 第一周: summary/25year/7month/1week.md
                  - 第二周: summary/25year/7month/2week.md
                  - 第三周: summary/25year/7month/3week.md
                  - 第四周: summary/25year/7month/4week.md
              - 8月:
                  - summary/25year/8month/index.md
                  - 第一周: summary/25year/8month/1week.md
                  - 第二周: summary/25year/8month/2week.md
                  - 第三周: summary/25year/8month/3week.md
                  - 第四周: summary/25year/8month/4week.md
              - 9月:
                  - summary/25year/9month/index.md
                  - 第一周: summary/25year/9month/1week.md
                  - 第二周: summary/25year/9month/2week.md
                  - 第三周: summary/25year/9month/3week.md
                  - 第四周: summary/25year/9month/4week.md
