site_name: cypress.blog
site_description: cypress的技术博客以及日常生活记录
site_author: cypress
site_url: https://cyprer.github.io/blog0/
theme:
  name: material
  features:
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - content.code.copy #代码复制
  palette:
    # 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式

    # 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

plugins:
  - search #搜索配置
  - include_dir_to_nav:
      sort_file: true
      sort_directory: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: Pale-illusions/my-mkdocs
      branch: main
      exclude:
        - index.md
        - tag.md
        - waline.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: iso_date
      enable_creation_date: false
      exclude:
        - index.md
        - tag.md
        - liuyanban.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
        - websitebeauty/linktech.md
  - blog: #博客配置
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #作者信息
  - tags:
      tags_file: tag.md #分类标签

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件


  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"


nav:
      - 笔记:
          - 数据结构:
              - 代码随想录:
                  - 数组:
                      - 二分查找: note/datastructure/array/binary-search.md
                      - 快慢指针: note/datastructure/array/fast-slow-pointer.md
                      - 双指针: note/datastructure/array/double-pointer.md
                      - 滑动窗口: note/datastructure/array/sliding-window.md
                      - 螺旋矩阵: note/datastructure/array/spiral-matrix.md
                      - 区间和: note/datastructure/array/interval-sum.md
                      - 分配土地: note/datastructure/array/land-allocation.md
              - 刷题日记:
                - 2025:
                  - 3月:
                    - 8号: note/datastructure/diary/2025/3month/8.md
                    - 9号: note/datastructure/diary/2025/3month/9.md
                    - 10号: note/datastructure/diary/2025/3month/10.md
                    - 11号: note/datastructure/diary/2025/3month/11.md
                    - 12号: note/datastructure/diary/2025/3month/12.md
                    - 13号: note/datastructure/diary/2025/3month/13.md
                    - 14号: note/datastructure/diary/2025/3month/14.md
                    - 15号: note/datastructure/diary/2025/3month/15.md
                    - 16号: note/datastructure/diary/2025/3month/16.md
                    - 17号: note/datastructure/diary/2025/3month/17.md
          - 计组:
            - csapp: note/cs_composition/csapp.md
            - cs61c:
                - knowledge:
                  - 内存管理: note/cs_composition/cs61c/knowledge/memory_management.md
                  - 浮点数: note/cs_composition/cs61c/knowledge/floating-point.md
                  - risv-v: note/cs_composition/cs61c/knowledge/risv-v.md
                - labs:
                  - lab1: note/cs_composition/cs61c/labs/lab1.md
                - projects:
                  - project1: note/cs_composition/cs61c/projects/project1.md
          - 计网: 
            - note/cs_net/cs-net.md
          - 操作系统: 
            - note/os/os.md
          - 其他:
            - 图灵完备: note/others/turing.md
            - 建站教程: note/others/site-construction.md
          - ssm:
            - hmdp: 
              - 登录: note/ssm/hmdp/login.md
              - 优惠卷秒杀: note/ssm/hmdp/voucher.md
            - spring:  note/ssm/spring.md
            - springmvc: note/ssm/springmvc.md
            - mybatis: note/ssm/mybatis.md
          
        
      - summary:
          - 2025年:
              - 1月:
                  - 第一周: summary/25year/1month/1week.md
                  - 第二周: summary/25year/1month/2week.md
                  - 第三周: summary/25year/1month/3week.md
                  - 第四周: summary/25year/1month/4week.md
              - 2月:
                  - 第一周: summary/25year/2month/1week.md
                  - 第二周: summary/25year/2month/2week.md
                  - 第三周: summary/25year/2month/3week.md
                  - 第四周: summary/25year/2month/4week.md
              - 3月:
                  - 第一周: summary/25year/3month/1week.md
                  - 第二周: summary/25year/3month/2week.md
                  - 第三周: summary/25year/3month/3week.md
